export default {
    ADD_PERSON: 'ADD_PERSON',
    REMOVE_PERSON: 'REMOVE_PERSON',
    UPDATE_PERSON: 'UPDATE_PERSON',
    SEND_MESSAGE: 'SEND_MESSAGE',
    UPDATE_MESSAGE_LIST: 'UPDATE_MESSAGE_LIST',
    MESSAGE_HANDLER: 'MESSAGE_HANDLER',
    SET_SOCKET: 'SET_SOCKET',
    SET_USER_ID: 'SET_USER_ID'
}